### ISSUE TITLE
Bug: Queries with additional criteria return unexpected results

### ISSUE THREAD

**Issue by janmeeus** [unionco/calendarize#3]
There is a problem when using additional criteria on queries, like limit:
```
{% set entries = craft.calendarize.upcoming(
  {
    section: ['events'],
    limit: 4
  }
) %}
```

This results in 2 errors:

1. Only one result returned. Expected result: 4.
2. The order of resulting entries is not the chronological order of the events.

If more information is needed, don't hesitate to ask!

**Comment by fvaldes33** [comment]
@janmeeus - Could you possible send me a copy of the database? Or maybe just send me the events you have entered?

Thanks

**Comment by janmeeus** [comment]
@fvaldes33 Thanks for the quick reply!
After updating to 1.1.12 no results are returned, even when using the simplest queries.
E.g. 
```
{% set entries = craft.calendarize.upcoming({
  section: ['events'] })
%}
```
I tried clearing the cache. No fix. Reverting to v1.1.9 did return results.

**Comment by fvaldes33** [comment]
@janmeeus - Could you send me a copy of your db? Would like to see where I am missing something. Just tried your above snippet on my testing DB and it still returns entries.

**Comment by janmeeus** [comment]
Sorry I can't do that, but here are the steps to recreate:

1. Create Calenderize field `calendar`.
2. Create new section `events` as a channel
3. Add the `calendar` field to the `events` section
4. In this order, add following entries: 
5. Christmas, 2019-12-25, Repeating yearly
6. Easter, 2019-04-21, Repeating yearly
7. New Year, 2019-01-01, Repeating yearly

Following code returns 0 results:
```
{% set entries = craft.calendarize.upcoming({
  section: ['events'] })
%}
<h3>{{ entries|length }}</h3>
```

Craft CMS version 3.1.4, Calendarize v1.1.12

**Comment by fvaldes33** [comment]
Took your steps and did find the issue - typo in the query itself.

`{% set entries = craft.calendarize.upcoming({ section: ['events'], limit: 1 }) %}`

```
Title: Easter
Type: events 
Start Date: 2019-04-21 
End Repeat Date: Never Ends
Next: 2019-04-21 @ 12:00 am 
Rule: yearly, starting from 4/21/19, until 1/25/24
```

`{% set entries = craft.calendarize.upcoming({ section: ['events'] }) %}`

```
Title: Easter 
Type: events 
Start Date: 2019-04-21 
End Repeat Date: Never Ends
Next: 2019-04-21 @ 12:00 am 
Rule: yearly, starting from 4/21/19, until 1/25/24

Title: Christmas 
Type: events 
Start Date: 2019-12-25 
End Repeat Date: Never Ends
Next: 2019-12-25 @ 12:00 am 
Rule: yearly, starting from 12/25/19, until 1/25/24

Title: New Year
Type: events 
Start Date: 2019-01-01 
End Repeat Date: Never Ends
Next: 2020-01-01 @ 12:00 am 
Rule: yearly, starting from 1/1/19, until 1/25/24
```

I also found a minor issue with the limits, so i moved the limit criteria to after the entries are sorted.

Fixed in 1.1.13 [3054dcb](https://github.com/unionco/calendarize/commit/3054dcbac09909e0634efee21a7e480d0d3b570a)

**Comment by janmeeus** [comment]
@fvaldes33 
Thanks for the quick fix!

There are two things that came up with some new testing (both times using "All Day" on):

1. When adding an occurence (not repeating) with startDate 2018-02-20 (so "in the past"), it still shows in the results when using `craft.calendarize.upcoming`

1. When adding a yearly occurence that lasts several days (e.g. 20-02-2019 to 24-02-2019), I can only display the startDate of the next occurence (`{{ event.calendarizeHandle.next }}`), but not the endDate of the next occurence.
